import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { copyFile, mkdir } from "node:fs/promises";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Source lives in src/main.ts
*/`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
		...builtinModules.map((m) => `node:${m}`),
	],
	loader: { ".swift": "text", ".ps1": "text" },
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	platform: "node",
});

if (prod) {
	await context.rebuild();
	// Keep a complete, ready-to-copy Obsidian plugin folder with every build.
	const pluginDir = "plugins/fingerprint-lock";
	await mkdir(pluginDir, { recursive: true });
	await Promise.all(["main.js", "manifest.json", "styles.css"].map((file) =>
		copyFile(file, `${pluginDir}/${file}`)
	));
	process.exit(0);
} else {
	await context.watch();
}
